theme: minima
title: My Blog
author: Marcus Shongo
email: mshon1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  My site provides an excellent service to help people become better at programming!

# social links
github_username:  mshon1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
